//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuImage
    {
        public long ImageId { get; set; }
        public string ImagePath { get; set; }
        public long MenuId { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
