//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantMenu
    {
        public long RestaurantMenuId { get; set; }
        public long MenuId { get; set; }
        public long RestaurantId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
